build:
  maxIssues: 0

complexity:
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    functionThreshold: 8
  TooManyFunctions:
    active: true
    thresholdInFiles: 20
    thresholdInClasses: 20

style:
  MagicNumber:
    active: true
    ignoreAnnotated: true
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  MaxLineLength:
    active: true
    maxLineLength: 120
  UnusedPrivateMember:
    active: true

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated: ['Composable']
  TopLevelPropertyNaming:
    active: true

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false
